language: python
python:
  - "2.7"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

# command to install dependencies
install:
    - pip install -r requirements.txt --use-mirrors
    - make build

# command to run tests
script:
    - nosetests
    - lettuce tests
