#!/bin/bash

main() {
    make -s build
    print_runtime > /dev/null
    print_runtime
}

print_runtime() {
    pid=$(start_server)
    runtime=$(time_command wait_for_server)
    baseline=$(time_command wait_for_server)
    echo $runtime - $baseline | bc
    kill -9 $pid
}

start_server() {
    export DEEVA_OPEN_BROWSER='False'
    pushd examples/helloworld 1>/dev/null
    ../../run_deeva.py HelloWorld 1>/dev/null &
    echo $!
    popd 1>/dev/null
}

time_command() {
    local cmd=$*
    TIMEFORMAT="%3R"
    (time $cmd) 2>&1
}

wait_for_server() {
    while true; do
        lsof -i :5000 > /dev/null
        if [[ $? == 0 ]]; then
            break
        fi
    done
}

main
