#!/bin/bash

start=$1
end=$2

main() {
    echo "commit, time"
    # hack to measure the beginning of time
    cp $(dirname $0)/start-time $(dirname $0)/xxx__start-time 
    starttime='`$(dirname $0)/xxx__start-time`'
    command="echo $hash, $starttime"
    $(dirname $0)/run-command-on-git-revisions -v $start $end "$command"
    rm $(dirname $0)/xxx__start-time 
}

# Get the hash
hash='`git log -1 --pretty=%h`'

main
