#!/bin/bash

start=$1
end=$2

main() {
    echo "commit, time"
    command="echo $hash, `$(dirname $0)/start-time`"
    $(dirname $0)/run-command-on-git-revisions -v $start $end "$command"
}

# Get the hash
hash='`git log -1 --pretty=%h`'

main
